services:
  robc-web:
    service_name: robc-web
    restart: always
    container_name: robc-web
    image: robc-web
    build: .
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm start
volumes:
  node_modules:

